### ISSUE TITLE
这与我整理的180个频道一模一样，我不知道怎么评价！

### ISSUE THREAD

**Issue by YueChan** [DangJin/awesome-iptv#2]
这与我整理的180个频道一模一样，我不知道怎么评价！

**Comment by DangJin** [comment]
对于未经作者同意对内容二创且未标明出处向大神真诚的道歉！
我现已在项目标明出处并链接您项目地址，同时也向你打赏了！
创作不易，应该珍惜每个人的劳动成果，我也期待与大佬后续的交流与学习。

![Snipaste_2024-06-15_21-41-16](https://github.com/DangJin/iptv_m3u8/assets/16586370/c8cd6bc0-5ccd-4b69-abc3-9efa199eceb3)
