### ISSUE TITLE
中国人最大的问题就是喜欢抄袭

### ISSUE THREAD

**Issue by bao3** [DangJin/awesome-iptv#3]
很难相信这是当代年轻人的价值观。

**Comment by YueChan** [comment]
我把凤凰卫视改成老挝ip了，看是否会原封不动照搬😄

**Comment by sztuxp** [comment]
开源的东西照抄，就不要基本的脸面了

**Comment by chengnan049** [comment]
![1000001082.png](https://github.com/DangJin/awesome-iptv/assets/46060083/fcf6d8c8-2918-44f5-aa43-fde7daec0437)

![1000001086.png](https://github.com/DangJin/awesome-iptv/assets/46060083/84c4bcd8-6706-47f5-9d41-dcb7799dedc3)

![1000001083.png](https://github.com/DangJin/awesome-iptv/assets/46060083/b65326d4-54cf-4bbc-bedc-3cba57fa71b3)

事发之后 YueChan 大佬在 Twitter 回应并单发推文，DangJin 回复该推文向仓库中注释并单发推文道歉，YueChan 觉得没事，标注一下就好，并删除了单发推文，但 DangJin 隐藏了 YueChan 的推文

**Comment by DangJin** [comment]
> 开源的东西照抄，就不要基本的脸面了

@chengnan049 不知阁下是否有使用咖啡的源并给咖啡打赏，不知是否也从来不用开源的项目，也不用盗版软件遵守自己君子的风范呢？

**Comment by YueChan** [comment]
人非圣贤，孰能无过？过而能改，善莫大焉。讨论到此结束，谢谢大家！

**Comment by chengnan049** [comment]
> > 开源的东西照抄，就不要基本的脸面了
> 
> @chengnan049 不知阁下是否有使用咖啡的源并给咖啡打赏，不知是否也从来不用开源的项目，也不用盗版软件遵守自己君子的风范呢？

1.我使用过咖啡的源，是给家里人用的，但电视两三个月都不见得开一次，经过升级之后，电视不能设置开机自动进入某软件了，看电视的频率更少了，点名批评 TCL
2.我还只是一名刚刚高中毕业的学生，暂未有这个财力来打赏，我也使用盗版软件，且数量不少，我的这点小钱大多都砸在了入正上，在这里说一声抱歉了！
3.我也使用开源项目，我没有什么技术，不过我很乐意帮他人，在某群发言有上万条，一旦有可以帮助他人的，我必定会给上原出处以及加群链接
4.` 开源的东西照抄，就不要基本的脸面了`， 这句话不是我说的哇，为啥@我呢？
5.我奇怪的是为何要隐藏咖啡在你推文下的评论呢？
